[libdefaults]
    default_realm = CANDYLAND.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false

[realms]
    CANDYLAND.LOCAL = {
        kdc = dc.candyland.local
        admin_server = dc.candyland.local
    }

[domain_realm]
    .candyland.local = CANDYLAND.LOCAL
    candyland.local = CANDYLAND.LOCAL
